SOURCE_TELEGRAM_CHANNEL = 'telegram_channel'
SOURCE_MANUAL_FORWARD = 'manual_forward'
SOURCE_WATCHLIST_SCOUT = 'watchlist_scout'
SOURCE_FRAMEHDR = 'framehdr'
SOURCE_TYPES = frozenset({SOURCE_TELEGRAM_CHANNEL, SOURCE_MANUAL_FORWARD, SOURCE_WATCHLIST_SCOUT, SOURCE_FRAMEHDR})

CHANNEL_ROLE_RESOURCE = 'RESOURCE'
CHANNEL_ROLE_MANUAL_INGEST = 'MANUAL_INGEST'
CHANNEL_ROLE_PUBLISH_ONLY = 'PUBLISH_ONLY'
CHANNEL_ROLE_SUCCESS_NOTIFICATION = 'SUCCESS_NOTIFICATION'
#: Roles allowed to feed the Scout resource index. PUBLISH_ONLY, SUCCESS_NOTIFICATION — and any
#: ordinary group chat — is deliberately excluded so future publishing
#: channels can never enter resource discovery or cause a self-loop.
SCOUT_ALLOWED_CHANNEL_ROLES = frozenset({CHANNEL_ROLE_RESOURCE, CHANNEL_ROLE_MANUAL_INGEST})
TRANSFER_MODE_OFF = 'OFF'
TRANSFER_MODE_MANUAL = 'MANUAL'
TRANSFER_MODE_AUTO = 'AUTO'

INGEST_QUEUED = 'QUEUED'
INGEST_RUNNING = 'RUNNING'
INGEST_COMPLETED = 'COMPLETED'
INGEST_FAILED = 'FAILED'
INGEST_NEEDS_REVIEW = 'NEEDS_REVIEW'
INGEST_SKIPPED = 'SKIPPED'

TRANSFER_QUEUED = 'QUEUED'
TRANSFER_RUNNING = 'RUNNING'
TRANSFER_RETRY_WAIT = 'RETRY_WAIT'
TRANSFER_COMPLETED = 'COMPLETED'
TRANSFER_SUCCESS = 'SUCCESS'
TRANSFER_FAILED = 'FAILED'
TRANSFER_CANCELLED = 'CANCELLED'
TRANSFER_SKIPPED = 'SKIPPED'
